### ISSUE TITLE
show the great idea at Tartu Mini Maker!

### ISSUE THREAD

**Issue by edmundlaugasson** [laurivosandi/butterknife#12]
The news in Estonian is here - http://makerfairetartu.ee/?p=301
It says that at 20th September 2015 there will be next event at Tartu's Science Park AHHAA about self-made projects. For registering write an e-mail to makerfaire@ahhaa.ee or register directly at: https://goo.gl/qYgwjW

**Comment by laurivosandi** [comment]
Didn't make it :/
